# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]
  workflow_run:
    workflows: ["Tests"]
    branches: [main]
    types: 
      - completed

permissions:
  contents: read

jobs:
  build_sdist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install setuptools
          pip install setuptools_scm
          pip install cmake-build-extension
      - name: Build package
        working-directory: ./scripts/pip
        run: python -m build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: ./scripts/pip/dist/*.tar.gz
      - name: Rename sdist for cibuildwheel
        working-directory: ./scripts/pip
        run: bash ./rename_dist.sh
      - uses: actions/upload-artifact@v4
        with:
          name: intermediate_sdist
          path: ./scripts/pip/sdist.tar.gz

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    needs: [build_sdist]
    env:
      LIBMLCONCEPTS_ISET_DISTRIBUTION: -mavx
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]

    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          python -m pip install cibuildwheel
      - uses: actions/download-artifact@v4
        with:
          name: intermediate_sdist
          path: .
      - name: Build wheels
        run: python -m cibuildwheel sdist.tar.gz --output-dir wheelhouse
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install --upgrade pipenv setuptools setuptools-scm wheel
        pip install cmake
        pip install pybind11
        pip install numpy
        pip install pandas
        pip install pytest
    - name: Run tests
      run: |
        mkdir build
        cd build
        cmake -Dpybind11_DIR=`pybind11-config --cmakedir` ..
        make all
        ctest
        pytest
  
  deploy:
    needs: [build_wheels, build_sdist, tests]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: dist
